[package]
name = "vivid"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2018"

[dependencies]
cgmath = "*"
specs = "0.14.3"
specs-derive = "0.4.0"
png = "0.14.0"
assert_approx_eq = "1.1.0"
